### ISSUE TITLE
bone和position模块

### ISSUE THREAD

**Issue by Tong-Hao741** [Deante-dx/TFAN#1]
请问bone和position模块都使用同一个模型predictor吗？

**Comment by Deante-dx** [comment]
对 同样的模型结构。 但是 是两个的模型分别训练，并没有共享参数。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Deante-dx/TFAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月14日(星期天) 中午1:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Deante-dx/TFAN] bone和position模块 (Issue #1)





 
请问bone和position模块都使用同一个模型predictor吗？

**Comment by Tong-Hao741** [comment]
嗯嗯感谢及时回复，打算拿TFAN作为baseline，很棒的工作！

**Comment by Tong-Hao741** [comment]
还有一个小问题，我看论文代码好像是用siMLPe的结构，我一直无法复现siMLPe的论文效果，请问你遇到这个问题了吗qaq

**Comment by Deante-dx** [comment]
有的&nbsp; 我也复现不出来






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Deante-dx/TFAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月14日(星期天) 中午1:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Deante-dx/TFAN] bone和position模块 (Issue #1)





 
还有一个小问题，我看论文代码好像是用siMLPe的结构，我一直无法复现siMLPe的论文效果，请问你遇到这个问题了吗qaq

**Comment by Tong-Hao741** [comment]
好的，谢谢学长！

**Comment by Deante-dx** [comment]
好嘞&nbsp; 谢谢你的认可




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Deante-dx/TFAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月14日(星期天) 中午1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Deante-dx/TFAN] bone和position模块 (Issue #1)





 
嗯嗯感谢及时回复，打算拿TFAN作为baseline，很棒的工作！

**Comment by Tong-Hao741** [comment]
学长不好意思又来麻烦你有一些问题想请教一下，这个LN_mid模块就是论文中指的轴归一化操作吗？
![image](https://github.com/Deante-dx/TFAN/assets/56951874/ad98f661-5e38-4917-a26d-90a5b16dd250)
还有一个疑问是仅训练bone和position在h36m上的误差结果如下：
![image](https://github.com/Deante-dx/TFAN/assets/56951874/ed51c44e-3f8c-4074-896c-b2c14bde7259)
![image](https://github.com/Deante-dx/TFAN/assets/56951874/45890025-1c72-4488-83f3-de5ba15e6794)
达不到论文中的如下效果
![image](https://github.com/Deante-dx/TFAN/assets/56951874/588dbb30-2835-4f99-a56f-a111b6736d58)
但是使用提供的检查点能够正常复现最终结果
![image](https://github.com/Deante-dx/TFAN/assets/56951874/0d367073-5585-4f0a-a58e-c256ba11e67a)
按照readme执行的，是我哪些操作有误吗

**Comment by Deante-dx** [comment]
LN_mid 就是 AN
复现不出来&nbsp; 暂时&nbsp; 我也不清楚什么问题&nbsp; &nbsp;我现在自己down代码跑一次试试




杜鑫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Deante-dx/TFAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月15日(星期一) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Deante-dx/TFAN] bone和position模块 (Issue #1)





 
学长不好意思又来麻烦你有一些问题想请教一下，这个LN_mid模块就是论文中指的轴归一化操作吗？
 image.png (view on web)
 还有一个疑问是仅训练bone和position在h36m上的误差结果如下：
 image.png (view on web)
 image.png (view on web)
 达不到论文中的如下效果
 image.png (view on web)
 但是使用提供的检查点能够正常复现最终结果
 image.png (view on web)
 按照readme执行的，是我哪些操作有误吗

**Comment by Tong-Hao741** [comment]
好的感谢学长，又跑了几次提升了0.0几个点，但是达不到检查点的效果 ~

**Comment by Deante-dx** [comment]
> 好的感谢学长，又跑了几次提升了0.0几个点，但是达不到检查点的效果 ~

![image](https://github.com/Deante-dx/TFAN/assets/65484822/346c77a3-542a-49f6-b855-c35761250d35)
![image](https://github.com/Deante-dx/TFAN/assets/65484822/d7cf90b1-179a-4737-a5b6-ff6d7702da74)
这是我跑的  这里能达到一模一样的结果，暂时不太清楚你的为什么复现不出来

**Comment by Tong-Hao741** [comment]
谢谢学长的数据，那我再换张卡试试~
