### ISSUE TITLE
BioMotionLab_NTroje数据集

### ISSUE THREAD

**Issue by Tong-Hao741** [Deante-dx/TFAN#2]
作者你好，我在AMASS网站里好像没有找到BioMotionLab_NTroje数据集的下载链接，能提供一下BioMotionLab_NTroje的下载地址吗，十分感谢

**Comment by Deante-dx** [comment]
BioMotionLab_NTroje就是这个BMLrub




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Deante-dx/TFAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月11日(星期二) 晚上9:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Deante-dx/TFAN] BioMotionLab_NTroje数据集 (Issue #2)





 
作者你好，我在AMASS网站里好像没有找到BioMotionLab_NTroje数据集的下载链接，能提供一下BioMotionLab_NTroje的下载地址吗，十分感谢

**Comment by Tong-Hao741** [comment]
十分感谢~
